steps:

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e  # Ensure the script exits on any error
    gcloud config set project asif-praveen-gke
    gcloud config set compute/zone asia-south1-a	
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/asif0257/test-nginx.git', '.']
  dir: /app

  # Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/asif-praveen-gke/nginx/nginx-sample:latest', '.']

  # Step 2: Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/asif-praveen-gke/nginx/nginx-sample:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud compute instance-templates create nginx-template 
    --machine-type=e2-medium 
    --network=projects/asif-praveen-gke/global/networks/siri-vpc-network 
    --image-family=Ubuntu-2004-LTS 
    --image-project=ubuntu-os-cloud 
    --boot-disk-type=pd-balanced 
    --boot-disk-size=10GB 
    --metadata=startup-script-url=gs://pikachu1/startup.sh 
    --tags=http-server

images:
  - 'asia-south1-docker.pkg.dev/asif-praveen-gke/nginx/nginx-sample:latest'

options:
  logging: CLOUD_LOGGING_ONLY  

  
